modLoader = "javafml"
loaderVersion = "*"
license = "CC-BY-NC-ND-4.0"
issueTrackerURL = "https://github.com/Faboslav/variants-and-ventures/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"
logoBlur = false
displayURL = "https://www.curseforge.com/minecraft/mc-mods/variants-and-ventures"

[[mixins]]
config = "variantsandventures-common.mixins.json"

[[mixins]]
config = "variantsandventures-neoforge.mixins.json"

[[dependencies."${modId}"]]
modId = "yet_another_config_lib_v3"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"
	[[dependencies."${modId}".mc-publish]]
		curseforge=667299
		modrinth="1eAoo2KR"

[modproperties."${modId}"]
catalogueImageIcon = "catalogue_icon.png"
catalogueBackground = "catalogue_background.png"
configuredBackground = "catalogue_background.png"